"""
PDF Generation Service for RakshaAI Documents
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from io import BytesIO
from datetime import datetime


class PDFGeneratorService:
    """Service to generate PDF documents"""
    
    @staticmethod
    def generate_document_pdf(
        document_type: str,
        document_content: str,
        user_name: str = "Citizen"
    ) -> BytesIO:
        """
        Generate a PDF from document content
        
        Args:
            document_type: Type of document (RTI, Complaint, etc.)
            document_content: Full text content of the document
            user_name: Name of the user generating the document
            
        Returns:
            BytesIO buffer containing the PDF
        """
        buffer = BytesIO()
        
        # Create PDF with A4 page size and margins
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )
        
        # Container for PDF elements
        elements = []
        
        # Define styles
        styles = getSampleStyleSheet()
        
        # Title style
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=16,
            textColor='#1a1a1a',
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        # Body style
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=11,
            textColor='#333333',
            spaceAfter=12,
            alignment=TA_LEFT,
            fontName='Helvetica',
            leading=16
        )
        
        # Add title
        title_text = document_type.replace('_', ' ').title()
        title = Paragraph(title_text, title_style)
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))
        
        # Add generated by info
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor='#666666',
            alignment=TA_CENTER
        )
        
        generated_text = f"Generated by RakshaAI on {datetime.now().strftime('%d %B %Y, %I:%M %p')}"
        generated = Paragraph(generated_text, footer_style)
        elements.append(generated)
        elements.append(Spacer(1, 0.3*inch))
        
        # Process document content - split by newlines and create paragraphs
        lines = document_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                # Add small spacer for empty lines
                elements.append(Spacer(1, 0.1*inch))
            else:
                # Escape special characters for reportlab
                line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                
                # Check if line looks like a heading (short, uppercase, or ends with :)
                if (len(line) < 50 and line.isupper()) or (line.endswith(':') and len(line) < 80):
                    heading_style = ParagraphStyle(
                        'Heading',
                        parent=styles['Heading2'],
                        fontSize=12,
                        textColor='#1a1a1a',
                        spaceAfter=8,
                        spaceBefore=12,
                        fontName='Helvetica-Bold'
                    )
                    para = Paragraph(line, heading_style)
                else:
                    para = Paragraph(line, body_style)
                
                elements.append(para)
        
        # Add footer with instructions
        elements.append(Spacer(1, 0.5*inch))
        instruction_style = ParagraphStyle(
            'Instruction',
            parent=styles['Normal'],
            fontSize=9,
            textColor='#666666',
            alignment=TA_LEFT,
            leftIndent=20,
            spaceAfter=6
        )
        
        instructions = [
            "📌 <b>Important Instructions:</b>",
            "• Print this document on A4 size paper",
            "• Sign where required",
            "• Attach supporting documents as mentioned",
            "• Keep a copy for your records",
            "• Send by registered post and keep the receipt as proof"
        ]
        
        for instruction in instructions:
            elements.append(Paragraph(instruction, instruction_style))
        
        # Add disclaimer
        elements.append(Spacer(1, 0.3*inch))
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=7,
            textColor='#999999',
            alignment=TA_CENTER
        )
        disclaimer = Paragraph(
            "This document is auto-generated by RakshaAI. Please verify all details before submission. "
            "For legal advice, consult a licensed advocate. Free legal aid: NALSA helpline 15100",
            disclaimer_style
        )
        elements.append(disclaimer)
        
        # Build PDF
        doc.build(elements)
        
        # Reset buffer position
        buffer.seek(0)
        return buffer
